<?php
// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Columns, two with gallery
 */
return array(
	'name'        => 'columns-two-with-gallery',
	'title'       => 'Two columns with a photo gallery',
	'description' => 'Heading with text and a photo gallery',
	'categories'  => array( 'appro-text' ),
	'content'     => '<!-- wp:group {"align":"full","style":{"spacing":{"margin":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} --><div class="wp-block-group alignfull" style="margin-top:var(--wp--preset--spacing--60);margin-bottom:var(--wp--preset--spacing--60)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"left":"var:preset|spacing|70"}}}} --><div class="wp-block-columns alignwide"><!-- wp:column --><div class="wp-block-column"><!-- wp:heading {"level":1} --><h1 class="wp-block-heading">Two columns with a gallery.</h1><!-- /wp:heading --><!-- wp:paragraph --><p>Bacon ipsum dolor amet beef ribs sausage pork sirloin pork chop. Sausage spare ribs tongue doner t-bone pastrami, ground round pancetta prosciutto pig ham. </p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Ham hock tail ham bacon brisket ground round filet mignon short ribs, capicola t-bone chislic cow. Flank sausage prosciutto pork belly filet mignon, corned beef doner ground round salami beef ribs ham hock.</p><!-- /wp:paragraph --><!-- wp:paragraph --><p>Brisket pancetta porchetta landjaeger, short loin t-bone chicken picanha boudin hamburger corned beef jerky shank. Jowl ball tip leberkas, picanha ribeye short. T-bone swine cow turducken, boudin pig beef jowl bacon ham hock shank prosciutto.</p><!-- /wp:paragraph --></div><!-- /wp:column --><!-- wp:column --><div class="wp-block-column"><!-- wp:gallery {"linkTo":"lightbox","style":{"spacing":{"blockGap":{"top":"10px","left":"10px"}}}} --><figure class="wp-block-gallery has-nested-images columns-default is-cropped"><!-- wp:image {"id":1046,"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="{{PLUGIN_URL}}images/yoga.jpg" alt="" class="wp-image-1046"/></figure><!-- /wp:image --><!-- wp:image {"id":994,"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="{{PLUGIN_URL}}images/surfing.jpg" alt="" class="wp-image-994"/></figure><!-- /wp:image --><!-- wp:image {"id":1230,"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="{{PLUGIN_URL}}images/skater.jpg" alt="" class="wp-image-1230"/></figure><!-- /wp:image --><!-- wp:image {"id":631,"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="{{PLUGIN_URL}}images/snowboarder.jpg" alt="" class="wp-image-631"/></figure><!-- /wp:image --><!-- wp:image {"id":510,"sizeSlug":"large","linkDestination":"none"} --><figure class="wp-block-image size-large"><img src="{{PLUGIN_URL}}images/profile-large.jpg" alt="" class="wp-image-510"/></figure><!-- /wp:image --></figure><!-- /wp:gallery --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->',
);