<?php
// Prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Query loop, featured with sidebar
 */
return array(
	'name'        => 'query-featured-with-sidebar',
	'title'       => 'Query with featured post and sidebar posts',
	'description' => 'A featured article (left), then sidebar with multiple other articles',
	'categories'  => array( 'appro-query' ),
	'content'     => '<!-- wp:group {"metadata":{"categories":["appro-text"],"patternName":"all-patterns-pro/columns-two-with-borders"},"align":"full","className":"is-style-default","style":{"spacing":{"margin":{"top":"var:preset|spacing|60","bottom":"var:preset|spacing|60"}}},"layout":{"type":"constrained"}} --><div class="wp-block-group alignfull is-style-default" style="margin-top:var(--wp--preset--spacing--60);margin-bottom:var(--wp--preset--spacing--60)"><!-- wp:columns {"align":"wide","style":{"spacing":{"blockGap":{"top":"var:preset|spacing|40","left":"var:preset|spacing|40"}}}} --><div class="wp-block-columns alignwide"><!-- wp:column {"width":"60%"} --><div class="wp-block-column" style="flex-basis:60%"><!-- wp:query {"queryId":2,"query":{"perPage":1,"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"taxQuery":null,"parents":[],"format":[]},"className":"is-style-default"} --><div class="wp-block-query is-style-default"><!-- wp:post-template {"style":{"spacing":{"blockGap":"0"}}} --><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"auto"} /--><!-- wp:post-title {"level":3,"isLink":true,"style":{"spacing":{"margin":{"top":"0","bottom":"0"}}}} /--><!-- wp:post-excerpt {"excerptLength":20} /--><!-- /wp:post-template --></div><!-- /wp:query --></div><!-- /wp:column --><!-- wp:column {"width":"40%"} --><div class="wp-block-column" style="flex-basis:40%"><!-- wp:group {"className":"mobile-padding-left-0 mobile-padding-top-small","layout":{"type":"constrained"}} --><div class="wp-block-group mobile-padding-left-0 mobile-padding-top-small"><!-- wp:query {"queryId":2,"query":{"perPage":4,"pages":0,"offset":"1","postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"taxQuery":null,"parents":[],"format":[]},"className":"is-style-default"} --><div class="wp-block-query is-style-default"><!-- wp:post-template {"style":{"spacing":{"blockGap":"var:preset|spacing|40"}}} --><!-- wp:columns {"style":{"spacing":{"blockGap":{"left":"var:preset|spacing|20"},"margin":{"top":"0","bottom":"0"}}}} --><div class="wp-block-columns" style="margin-top:0;margin-bottom:0"><!-- wp:column {"width":"25%"} --><div class="wp-block-column" style="flex-basis:25%"><!-- wp:post-featured-image {"isLink":true,"aspectRatio":"1"} /--></div><!-- /wp:column --><!-- wp:column {"width":"75%","style":{"spacing":{"blockGap":"10px"}}} --><div class="wp-block-column" style="flex-basis:75%"><!-- wp:post-title {"level":5,"isLink":true,"style":{"spacing":{"margin":{"top":"0","bottom":"0"}}}} /--><!-- wp:post-excerpt {"excerptLength":20,"fontSize":"small"} /--></div><!-- /wp:column --></div><!-- /wp:columns --><!-- /wp:post-template --></div><!-- /wp:query --></div><!-- /wp:group --></div><!-- /wp:column --></div><!-- /wp:columns --></div><!-- /wp:group -->',
);